# Generated by Django 5.2.4 on 2025-07-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aprendiz",
            fields=[
                (
                    "id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("documento_identidad", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("teléfono", models.CharField(max_length=20)),
                ("correo", models.EmailField(max_length=254)),
                ("fecha_nacimiento", models.DateField()),
                ("ciudad", models.CharField(max_length=100)),
                ("programa", models.CharField(max_length=100)),
            ],
        ),
    ]
